./clang.sh c/ascii-invaders.c PAWS/L-I.PAW
./clang.sh c/asteroids.c PAWS/L-A.PAW
./clang.sh c/chess.c PAWS/L-C.PAW
./clang.sh c/demo.c PAWS/L-D.PAW
./clang.sh c/fractal.c PAWS/L-F.PAW
./clang.sh c/fractal-full.c PAWS/L-F2.PAW
./clang.sh c/invaders-from-scratch.c PAWS/L-IFS.PAW
./clang.sh c/jpeg-test.c PAWS/L-J.PAW
./clang.sh c/keyboard.c PAWS/L-K.PAW
./clang.sh c/life.c PAWS/L-L.PAW
./clang.sh c/maze.c PAWS/L-M.PAW
./clang.sh c/scale.c PAWS/L-S2.PAW
./clang.sh c/smttest.c PAWS/L-S.PAW
./clang.sh c/terminal-test.c PAWS/L-T.PAW
./clang.sh c/tune.c PAWS/L-T2.PAW

./clangF.sh c/fractal.c PAWS/LF-F.PAW
./clangF.sh c/fractal-full.c PAWS/LF-F2.PAW
./clangF.sh c/scale.c PAWS/LF-S2.PAW
./clangF.sh c/terminal-test.c PAWS/LF-T.PAW

./clangB.sh c/ascii-invaders.c PAWS/LB-I.PAW
./clangB.sh c/asteroids.c PAWS/LB-A.PAW
./clangB.sh c/chess.c PAWS/LB-C.PAW
./clangB.sh c/demo.c PAWS/LB-D.PAW
./clangB.sh c/fractal.c PAWS/LB-F.PAW
./clangB.sh c/fractal-full.c PAWS/LB-F2.PAW
./clangB.sh c/invaders-from-scratch.c PAWS/LB-IFS.PAW
./clangB.sh c/jpeg-test.c PAWS/LB-J.PAW
./clangB.sh c/life.c PAWS/LB-L.PAW
./clangB.sh c/maze.c PAWS/LB-M.PAW
./clangB.sh c/scale.c PAWS/LB-S2.PAW
./clangB.sh c/smttest.c PAWS/LB-S.PAW
./clangB.sh c/terminal-test.c PAWS/LB-T.PAW
./clangB.sh c/tune.c PAWS/LB-T2.PAW

./clangBF.sh c/fractal.c PAWS/LBF-F.PAW
./clangBF.sh c/fractal-full.c PAWS/LBF-F2.PAW
./clangBF.sh c/scale.c PAWS/LBF-S2.PAW
./clangBF.sh c/terminal-test.c PAWS/LBF-T.PAW
