./clang.sh c/ascii-invaders.c PAWS/LLVM-I.PAW
./clang.sh c/asteroids.c PAWS/LLVM-A.PAW
./clang.sh c/chess.c PAWS/LLVM-C.PAW
./clang.sh c/demo.c PAWS/LLVM-D.PAW
./clang.sh c/fractal.c PAWS/LLVM-F.PAW
./clang.sh c/fractal-full.c PAWS/LLVM-F2.PAW
./clang.sh c/jpeg-test.c PAWS/LLVM-J.PAW
./clang.sh c/invaders-from-scratch.c PAWS/LLVM-IFS.PAW
./clang.sh c/life.c PAWS/LLVM-L.PAW
./clang.sh c/maze.c PAWS/LLVM-M.PAW
#./clang.sh c/ppm2bitmap.c PAWS/LLVM-P.PAW
./clang.sh c/smttest.c PAWS/LLVM-S.PAW
./clang.sh c/terminal-test.c PAWS/LLVM-T.PAW
./clang.sh c/tune.c PAWS/LLVM-T2.PAW

#./clangF.sh c/ascii-invaders.c PAWS/LLVMF-I.PAW
#./clangF.sh c/asteroids.c PAWS/LLVMF-A.PAW
#./clangF.sh c/chess.c PAWS/LLVMF-C.PAW
#./clangF.sh c/demo.c PAWS/LLVMF-D.PAW
./clangF.sh c/fractal.c PAWS/LLVMF-F.PAW
./clangF.sh c/fractal-full.c PAWS/LLVMF-F2.PAW
#./clangF.sh c/jpeg-test.c PAWS/LLVMF-J.PAW
#./clangF.sh c/life.c PAWS/LLVMF-L.PAW
#./clangF.sh c/maze.c PAWS/LLVMF-M.PAW
#./clangF.sh c/ppm2bitmap.c PAWS/LLVMF-P.PAW
#./clangF.sh c/smttest.c PAWS/LLVMF-S.PAW
./clangF.sh c/terminal-test.c PAWS/LLVMF-T.PAW
#./clangF.sh c/tune.c PAWS/LLVMF-T2.PAW
