./clangB.sh c/ascii-invaders.c PAWS/L-I.PAW
./clangB.sh c/asteroids.c PAWS/L-A.PAW
./clangB.sh c/chess.c PAWS/L-C.PAW
./clangB.sh c/demo.c PAWS/L-D.PAW
./clangB.sh c/fractal.c PAWS/L-F.PAW
./clangB.sh c/fractal-full.c PAWS/L-F2.PAW
./clangB.sh c/invaders-from-scratch.c PAWS/L-IFS.PAW
./clangB.sh c/jpeg-test.c PAWS/L-J.PAW
./clangB.sh c/keyboard.c PAWS/L-K.PAW
./clangB.sh c/life.c PAWS/L-L.PAW
./clangB.sh c/maze.c PAWS/L-M.PAW
./clangB.sh c/scale.c PAWS/L-S2.PAW
./clangB.sh c/smttest.c PAWS/L-S.PAW
./clangB.sh c/terminal-test.c PAWS/L-T.PAW
./clangB.sh c/tune.c PAWS/L-T2.PAW

./clangBF.sh c/fractal.c PAWS/LF-F.PAW
./clangBF.sh c/fractal-full.c PAWS/LF-F2.PAW
./clangBF.sh c/scale.c PAWS/LF-S2.PAW
./clangBF.sh c/terminal-test.c PAWS/LF-T.PAW
