./compile.sh c/ascii-invaders.c PAWS/INVADERS.PAW
./compile.sh c/asteroids.c PAWS/ASTROIDS.PAW
./compile.sh c/chess.c PAWS/CHESS.PAW
./compile.sh c/demo.c PAWS/DEMO.PAW
./compile.sh c/fractal.c PAWS/FRACTAL.PAW
./compile.sh c/fractal-full.c PAWS/FRACTAL2.PAW
./compile.sh c/jpeg-test.c PAWS/JPEG.PAW
./compile.sh c/invaders-from-scratch.c PAWS/IFS.PAW
./compile.sh c/life.c PAWS/LIFE.PAW
./compile.sh c/maze.c PAWS/3DMAZE.PAW
#./compile.sh c/ppm2bitmap.c PAWS/PPM2BMP.PAW
./compile.sh c/smttest.c PAWS/SMT.PAW
./compile.sh c/terminal-test.c PAWS/TERMINAL.PAW
./compile.sh c/tune.c PAWS/TUNE.PAW

#./compileF.sh c/ascii-invaders.c PAWS/GCCF-I.PAW
#./compileF.sh c/asteroids.c PAWS/GCCF-A.PAW
#./compileF.sh c/chess.c PAWS/GCCF-C.PAW
#./compileF.sh c/demo.c PAWS/GCCF-D.PAW
./compileF.sh c/fractal.c PAWS/GCCF-F.PAW
./compileF.sh c/fractal-full.c PAWS/GCCF-F2.PAW
#./compileF.sh c/jpeg-test.c PAWS/GCCF-J.PAW
#./compileF.sh c/life.c PAWS/GCCF-L.PAW
#./compileF.sh c/maze.c PAWS/GCCF-M.PAW
#./compileF.sh c/ppm2bitmap.c PAWS/GCCF-P.PAW
#./compileF.sh c/smttest.c PAWS/GCCF-S.PAW
./compileF.sh c/terminal-test.c PAWS/GCCF-T.PAW
#./compileF.sh c/tune.c PAWS/GCCF-T2.PAW

